#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
test_indicator

@author: jdiedrichsen
"""
import sys
print(sys.path)
sys.path.append('/Users/jdiedrichsen/Python')
import unittest
import PcmPy as pcm
import numpy as np
import pickle

# class TestInference(unittest.TestCase):
f = open('/Users/jdiedrichsen/Python/PcmPy/demos/data_finger7T.p','rb')
Y,M = pickle.load(f)
f.close()
MC = []
MC.append(pcm.ModelComponent('muscle',M[0].G))
MC.append(pcm.ModelComponent('natural',M[1].G))
MC.append(pcm.ModelComponent('muscle+nat',[M[0].G,M[1].G]))

Z, X, YY, n_channel, Noise, G_hat = pcm.inference.set_up_fit(Y[0])
G,Sig = pcm.util.est_G_crossval(Y[0].measurements, Z,
                                Y[0].obs_descriptors['part_vec'])
theta0 = [np.ones((2,7)) * np.array([[-1,0.1]]).T]*2
opt = {'verbose':2}
T, theta = pcm.inference.fit_model_individ(Y,MC,optim_param=opt)
pass