#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
test_indicator

@author: jdiedrichsen
"""
import sys
print(sys.path)
sys.path.append('/Users/jdiedrichsen/Python')
import unittest
# Import necessary libraries
import PcmPy as pcm
import numpy as np
import pickle
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from numpy import exp, sqrt
from sklearn.linear_model import Ridge, LinearRegression
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import make_scorer
import time
from test_regression_performance import r2_score, method_compare, pcm_performance, likelihood_compare


# class TestInference(unittest.TestCase):
TL = pd.DataFrame()
comp  = np.array([0,0,0,0,0,1,1,1,1,1,2,2,2,2,2,3,3,3,3,3]) # 20 regressors in 4 groups
Q = comp.shape[0]
theta = np.array([0.0,-2.0,-3.0,-1.0,1.0]) # Theta's for simulation 
for P in [100]:
    for N in [100,200,400,600,800,1000]:
        D = likelihood_compare(comp, theta, P = P, N = N)
        D['N']=N
        D['P']=P
        D['Q']=Q
        TL = TL.append(D, ignore_index=True)